# Generated by Django 3.1.2 on 2020-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('College_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(blank=True, max_length=10)),
                ('GitHublink', models.URLField(max_length=500)),
                ('Linkedin', models.URLField(max_length=500)),
                ('Instagram', models.URLField(max_length=500)),
                ('project1', models.TextField()),
                ('project2', models.TextField(blank=True)),
                ('project3', models.TextField(blank=True)),
                ('project4', models.TextField(blank=True)),
                ('Hobbies', models.TextField()),
            ],
        ),
    ]
